package database;
// Generated Oct 29, 2019 1:37:00 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Messege generated by hbm2java
 */
public class Messege  implements java.io.Serializable {


     private Integer idmessege;
     private User userByTomsg;
     private User userByFrommsg;
     private String messege;
     private Date datetime;

    public Messege() {
    }

	
    public Messege(User userByTomsg, User userByFrommsg) {
        this.userByTomsg = userByTomsg;
        this.userByFrommsg = userByFrommsg;
    }
    public Messege(User userByTomsg, User userByFrommsg, String messege, Date datetime) {
       this.userByTomsg = userByTomsg;
       this.userByFrommsg = userByFrommsg;
       this.messege = messege;
       this.datetime = datetime;
    }
   
    public Integer getIdmessege() {
        return this.idmessege;
    }
    
    public void setIdmessege(Integer idmessege) {
        this.idmessege = idmessege;
    }
    public User getUserByTomsg() {
        return this.userByTomsg;
    }
    
    public void setUserByTomsg(User userByTomsg) {
        this.userByTomsg = userByTomsg;
    }
    public User getUserByFrommsg() {
        return this.userByFrommsg;
    }
    
    public void setUserByFrommsg(User userByFrommsg) {
        this.userByFrommsg = userByFrommsg;
    }
    public String getMessege() {
        return this.messege;
    }
    
    public void setMessege(String messege) {
        this.messege = messege;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }




}


