package database;
// Generated Oct 29, 2019 1:37:00 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int mobile;
     private String name;
     private String password;
     private String city;
     private String gender;
     private Set<Messege> messegesForFrommsg = new HashSet<Messege>(0);
     private Set<Messege> messegesForTomsg = new HashSet<Messege>(0);

    public User() {
    }

	
    public User(int mobile) {
        this.mobile = mobile;
    }
    public User(int mobile, String name, String password, String city, String gender, Set<Messege> messegesForFrommsg, Set<Messege> messegesForTomsg) {
       this.mobile = mobile;
       this.name = name;
       this.password = password;
       this.city = city;
       this.gender = gender;
       this.messegesForFrommsg = messegesForFrommsg;
       this.messegesForTomsg = messegesForTomsg;
    }
   
    public int getMobile() {
        return this.mobile;
    }
    
    public void setMobile(int mobile) {
        this.mobile = mobile;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Set<Messege> getMessegesForFrommsg() {
        return this.messegesForFrommsg;
    }
    
    public void setMessegesForFrommsg(Set<Messege> messegesForFrommsg) {
        this.messegesForFrommsg = messegesForFrommsg;
    }
    public Set<Messege> getMessegesForTomsg() {
        return this.messegesForTomsg;
    }
    
    public void setMessegesForTomsg(Set<Messege> messegesForTomsg) {
        this.messegesForTomsg = messegesForTomsg;
    }




}


