package database;
// Generated Nov 1, 2019 2:43:52 PM by Hibernate Tools 3.6.0



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer id;
     private Seller seller;
     private String brand;
     private String model;
     private double price;
     private int qty;
     private String disc;
     private String imgUrl;

    public Product() {
    }

	
    public Product(String brand, String model, double price, int qty, String disc, String imgUrl) {
        this.brand = brand;
        this.model = model;
        this.price = price;
        this.qty = qty;
        this.disc = disc;
        this.imgUrl = imgUrl;
    }
    public Product(Seller seller, String brand, String model, double price, int qty, String disc, String imgUrl) {
       this.seller = seller;
       this.brand = brand;
       this.model = model;
       this.price = price;
       this.qty = qty;
       this.disc = disc;
       this.imgUrl = imgUrl;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Seller getSeller() {
        return this.seller;
    }
    
    public void setSeller(Seller seller) {
        this.seller = seller;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public String getDisc() {
        return this.disc;
    }
    
    public void setDisc(String disc) {
        this.disc = disc;
    }
    public String getImgUrl() {
        return this.imgUrl;
    }
    
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }




}


