package database;
// Generated Nov 4, 2019 8:49:21 AM by Hibernate Tools 3.6.0



/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer idcart;
     private Product product;
     private Customer customer;
     private Integer qty;

    public Cart() {
    }

	
    public Cart(Product product, Customer customer) {
        this.product = product;
        this.customer = customer;
    }
    public Cart(Product product, Customer customer, Integer qty) {
       this.product = product;
       this.customer = customer;
       this.qty = qty;
    }
   
    public Integer getIdcart() {
        return this.idcart;
    }
    
    public void setIdcart(Integer idcart) {
        this.idcart = idcart;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


