package database;
// Generated Nov 4, 2019 8:49:21 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer idcustomer;
     private String username;
     private String password;
     private Set<Cart> carts = new HashSet<Cart>(0);

    public Customer() {
    }

    public Customer(String username, String password, Set<Cart> carts) {
       this.username = username;
       this.password = password;
       this.carts = carts;
    }
   
    public Integer getIdcustomer() {
        return this.idcustomer;
    }
    
    public void setIdcustomer(Integer idcustomer) {
        this.idcustomer = idcustomer;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }




}


